export interface SkillLevel {
  level: number;
  title: string;
  description: string;
  xpRequired: number;
}

export interface Skill {
  id: string;
  name: string;
  icon: string;
  branch: string;
  maxLevel: number;
  levels: SkillLevel[];
}

export interface Branch {
  id: string;
  name: string;
  icon: string;
  color: string;
}

export interface EvidenceRecord {
  type: 'certificate' | 'project' | 'self_assessment' | 'peer_review' | 'contribution' | 'publication';
  title?: string;
  url?: string;
  description?: string;
}

export interface UserSkillRecord {
  skillId: string;
  currentLevel: number;
  xp: number;
  evidence?: EvidenceRecord[];
}

export interface Profile {
  username: string;
  displayName: string;
  bio: string;
  avatarEmoji: string;
  entityType: 'human' | 'ai_agent';
  privacy: 'public' | 'friends' | 'private';
  skills: UserSkillRecord[];
  totalXp: number;
}

// ---------- Branches ----------

export const BRANCHES: Branch[] = [
  { id: 'engineering', name: 'Engineering', icon: '⚙️', color: '#6366f1' },
  { id: 'ai_ml', name: 'AI / ML', icon: '🤖', color: '#8b5cf6' },
  { id: 'cloud_infra', name: 'Cloud / Infra', icon: '☁️', color: '#0ea5e9' },
  { id: 'data', name: 'Data', icon: '📊', color: '#f97316' },
  { id: 'product', name: 'Product', icon: '🎯', color: '#06b6d4' },
  { id: 'design', name: 'Design', icon: '🎨', color: '#f59e0b' },
  { id: 'soft_skills', name: 'Soft Skills', icon: '🌟', color: '#10b981' },
];

// ---------- Skills ----------

const STD_XP = [0, 100, 300, 600, 1000, 1600, 2400, 3500, 5000, 7500];
const STD_TITLES = ['Aware', 'Beginner', 'Practitioner', 'Skilled', 'Proficient', 'Advanced', 'Expert', 'Master', 'Grand Master', 'World Class'];

function levels(descs: string[]): SkillLevel[] {
  return descs.map((description, i) => ({
    level: i + 1,
    title: STD_TITLES[i],
    description,
    xpRequired: STD_XP[i],
  }));
}

export const SKILLS: Skill[] = [

  // ── Engineering ─────────────────────────────────────────────────────────────

  {
    id: 'typescript',
    name: 'TypeScript',
    icon: '🔷',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Can read TypeScript code and understand basic type annotations.',
      'Writes typed interfaces and basic generics. Configures tsconfig.',
      'Uses advanced generics, utility types (Partial, Pick, Omit). Resolves type errors confidently.',
      'Designs typed libraries and APIs. Uses conditional types and mapped types.',
      'Architects entire codebases in strict TypeScript. Writes complex type transformations.',
      'Contributes to DefinitelyTyped. Understands TypeScript internals and variance.',
      'Authors TypeScript compiler plugins. Designs zero-overhead abstraction layers.',
      'Pushes the boundaries of what TypeScript\'s type system can express.',
      'Contributes to TypeScript language spec. Recognized by the community.',
      'Among the top 100 TypeScript practitioners globally. Shapes the language direction.',
    ]),
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    icon: '🟨',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands variables, functions, and basic DOM manipulation.',
      'Writes async code with promises and callbacks. Familiar with ES6+ syntax.',
      'Masters closures, prototypes, event loop, and modern JS patterns.',
      'Builds complex client-side apps. Deep knowledge of the event loop and V8.',
      'Architects scalable JS systems. Performance optimization expertise.',
      'JavaScript engine internals knowledge. Contributes to polyfills and standards.',
      'TC39 contributor or author of widely-used JS libraries.',
      'Shapes the JavaScript ecosystem at a deep level.',
      'TC39 committee member. Proposed accepted language features.',
      'Defined the modern JavaScript era. Author of foundational libraries.',
    ]),
  },
  {
    id: 'react',
    name: 'React',
    icon: '⚛️',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands component model. Can follow a React tutorial.',
      'Builds simple UIs with hooks (useState, useEffect). Passes props correctly.',
      'Manages state with context/reducers. Optimizes with memo and callback.',
      'Builds reusable component libraries. Understands render cycles deeply.',
      'Architects large React apps. Deep knowledge of concurrent features.',
      'Writes custom renderers. Performance-optimizes complex interactive UIs.',
      'Contributes to React ecosystem libraries. Designs novel patterns.',
      'Deep understanding of React Fiber reconciler.',
      'React core contributor or recognized thought leader.',
      'Shapes React ecosystem at the highest level.',
    ]),
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    icon: '▲',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Has deployed a basic Next.js app. Understands pages vs. app router.',
      'Uses SSR, SSG, and ISR. Manages routing and API routes.',
      'Implements server components, streaming, and advanced caching strategies.',
      'Architects full-stack apps with Next.js. Optimizes Core Web Vitals.',
      'Builds production Next.js apps at scale. Deep understanding of rendering.',
      'Contributes to Next.js community. Optimizes complex deployment setups.',
      'Next.js expert recognized by the community. Speaks at conferences.',
      'Shapes Next.js ecosystem patterns and best practices.',
      'Core contributor to Next.js or Vercel. Influences roadmap.',
      'Among the top architects of modern Next.js applications globally.',
    ]),
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    icon: '🟩',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Can run a basic Node.js server and use npm packages.',
      'Builds REST APIs with Express or Fastify. Manages package.json.',
      'Handles async patterns (streams, events, workers). Writes middleware.',
      'Builds production-grade Node.js services. Understands libuv and V8 internals.',
      'Architects high-throughput Node.js backends. Performance tuning expertise.',
      'Contributes to Node.js core or widely used packages.',
      'Node.js core team contributor. Deep internals knowledge.',
      'Shapes Node.js evolution and ecosystem standards.',
      'Technical Steering Committee level influence on Node.js.',
      'Foundational contributor to the Node.js runtime or its major dependencies.',
    ]),
  },
  {
    id: 'python',
    name: 'Python',
    icon: '🐍',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Can write basic Python scripts with loops and functions.',
      'Uses standard library, writes classes, handles exceptions.',
      'Writes idiomatic Python with list comprehensions, generators, decorators.',
      'Builds packages, uses async/await, proficiency with type hints.',
      'Architects production Python services. Performance optimization expertise.',
      'Python internals knowledge. Writes C extensions or CPython patches.',
      'Python core contributor or widely used library author.',
      'Shapes Python language evolution.',
      'Python Steering Council level influence.',
      'One of the most recognized Python contributors globally.',
    ]),
  },
  {
    id: 'golang',
    name: 'Go',
    icon: '🐹',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands Go syntax. Can read and modify a Go program.',
      'Writes goroutines, channels, and basic HTTP servers.',
      'Uses interfaces, embedding, and idiomatic Go patterns.',
      'Builds production Go services. Proficient with concurrency primitives.',
      'Architects high-performance Go systems. Memory and CPU profiling expertise.',
      'Contributes to Go ecosystem libraries. Deep runtime knowledge.',
      'Go contributor or author of major Go OSS projects.',
      'Shapes Go patterns and idioms at an industry level.',
      'Go core team contributor. Influences language proposals.',
      'Foundational contributor to the Go runtime or standard library.',
    ]),
  },
  {
    id: 'rust',
    name: 'Rust',
    icon: '🦀',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands ownership and borrowing concepts. Can read Rust code.',
      'Writes safe Rust programs. Uses cargo and common crates.',
      'Tames the borrow checker confidently. Uses lifetimes and traits effectively.',
      'Builds production Rust services with async (tokio). No-std environments.',
      'Writes high-performance, safe systems code. Deep understanding of unsafe.',
      'Contributes to major Rust crates. Deep knowledge of the compiler.',
      'Rust core contributor or author of foundational crates.',
      'Shapes Rust idioms and patterns at an ecosystem level.',
      'Rust language team contributor. Authors accepted RFCs.',
      'Among the most influential Rust practitioners globally.',
    ]),
  },
  {
    id: 'java',
    name: 'Java',
    icon: '☕',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands Java syntax and OOP basics.',
      'Builds Java applications with Spring Boot or standard libraries.',
      'Uses design patterns, dependency injection, and concurrency APIs.',
      'Builds large-scale Java systems. Deep JVM knowledge.',
      'Tunes JVM performance. Architects enterprise Java applications.',
      'JVM internals expertise. Deep Spring framework knowledge.',
      'Author of widely-used Java libraries or Spring contributor.',
      'Shapes Java ecosystem and enterprise architecture patterns.',
      'JVM language designer or Java platform contributor.',
      'One of the top Java architects globally.',
    ]),
  },
  {
    id: 'sql',
    name: 'SQL',
    icon: '🗄️',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Writes basic SELECT, INSERT, UPDATE, DELETE queries.',
      'Uses JOINs, WHERE clauses, and aggregate functions.',
      'Writes subqueries, CTEs, and window functions. Understands indexes.',
      'Optimizes slow queries. Designs normalized schemas.',
      'Deep query optimization expertise. Uses EXPLAIN plans effectively.',
      'Architects complex database schemas for large-scale systems.',
      'Database internals expert. Contributes to DB tooling.',
      'Shapes database architecture patterns at an industry level.',
      'Core contributor to a major SQL database engine.',
      'Foundational contributor to database theory or major DB systems.',
    ]),
  },
  {
    id: 'api_design',
    name: 'API Design',
    icon: '🔌',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands what REST APIs are. Can consume an API.',
      'Designs basic CRUD REST APIs. Knows HTTP methods and status codes.',
      'Designs versioned, documented APIs. Familiar with OpenAPI/Swagger.',
      'Designs scalable, developer-friendly APIs. Handles pagination and filtering well.',
      'Architects APIs for large platforms. Deep understanding of REST and GraphQL.',
      'Designs API strategies for orgs. Authors API design guidelines.',
      'Recognized API design expert. Speaker and author on API design.',
      'Shapes industry API design standards.',
      'Core contributor to API standards (OpenAPI, gRPC, etc.).',
      'Among the most influential API designers globally.',
    ]),
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    icon: '🔗',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands GraphQL queries vs. REST. Can run a query in GraphiQL.',
      'Writes queries, mutations, and subscriptions. Uses Apollo Client.',
      'Builds a GraphQL server with resolvers. Understands schema design.',
      'Optimizes N+1 queries with DataLoader. Designs scalable schemas.',
      'Architects production GraphQL APIs. Federation and microservices expertise.',
      'Deep Apollo/Relay knowledge. Contributes to GraphQL tooling.',
      'Author of major GraphQL libraries or recognized community expert.',
      'Shapes GraphQL ecosystem and specification.',
      'GraphQL specification contributor or working group member.',
      'Foundational contributor to the GraphQL ecosystem.',
    ]),
  },
  {
    id: 'testing',
    name: 'Testing & QA',
    icon: '✅',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands why testing matters. Can follow a testing tutorial.',
      'Writes unit tests with Jest or pytest. Achieves basic coverage.',
      'Writes integration and E2E tests. Uses mocking effectively.',
      'Designs testing strategies. TDD practitioner. High-quality test suites.',
      'Owns quality strategy for a product. Performance and load testing.',
      'Builds testing infrastructure. Contract testing and mutation testing.',
      'Testing thought leader. Author of testing frameworks or tools.',
      'Shapes testing culture and strategy at an organizational level.',
      'Industry-recognized expert. Contributes to testing standards.',
      'Defined modern software testing practices.',
    ]),
  },
  {
    id: 'system_design',
    name: 'System Design',
    icon: '🏗️',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Knows what a load balancer and database are.',
      'Can design a simple 3-tier web app architecture.',
      'Designs systems for 10K users. Knows CAP theorem basics.',
      'Designs sharded databases, message queues, caching layers.',
      'Architects systems for 1M+ users with clear trade-offs documented.',
      'Designs multi-region, highly available distributed systems.',
      'Architects systems like Twitter, Uber, or Stripe from scratch.',
      'Shapes organizational architecture standards.',
      'Published thought leader in distributed systems.',
      'Defines industry patterns. Author of seminal papers.',
    ]),
  },
  {
    id: 'git',
    name: 'Git',
    icon: '🌿',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Can clone a repo, commit, and push. Understands basic version control.',
      'Uses branches, merges, and pull requests. Resolves basic conflicts.',
      'Uses rebase, cherry-pick, and bisect. Understands git internals.',
      'Designs branching strategies (GitFlow, trunk-based). Manages complex merges.',
      'Git workflow expert. Trains teams on advanced git usage.',
      'Deep git internals knowledge. Contributes to git tooling.',
      'Author of git tooling or recognized community expert.',
      'Shapes git workflow standards at an organizational level.',
      'Core contributor to git or widely-used git tooling.',
      'Foundational contributor to git or distributed version control.',
    ]),
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: '🐳',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands what containers are. Can run a docker pull and docker run.',
      'Writes Dockerfiles. Builds and tags images. Uses docker-compose.',
      'Optimizes image layers. Multi-stage builds. Container networking.',
      'Builds production container workflows. Registry management.',
      'Deep container internals knowledge. Security hardening.',
      'Designs container platforms and orchestration strategies.',
      'Docker ecosystem contributor or expert trainer.',
      'Shapes container standards and best practices at scale.',
      'Core contributor to container tooling or OCI specification.',
      'Foundational contributor to containerization technology.',
    ]),
  },
  {
    id: 'database_design',
    name: 'Database Design',
    icon: '🗃️',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands tables, rows, and foreign keys.',
      'Designs normalized schemas. Chooses between SQL and NoSQL.',
      'Designs schemas with indexes, constraints, and migrations.',
      'Models complex domains. Balances normalization vs. performance.',
      'Architects data models for high-scale applications.',
      'Deep expertise across relational, document, and graph databases.',
      'Database architecture thought leader. Contributes to DB tooling.',
      'Shapes data architecture standards for large organizations.',
      'Recognized expert across multiple database paradigms.',
      'Foundational contributor to database design theory.',
    ]),
  },
  {
    id: 'css',
    name: 'CSS / Tailwind',
    icon: '🎨',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands box model and basic selectors.',
      'Builds simple layouts with flexbox. Uses Tailwind utility classes.',
      'Masters CSS Grid and complex layouts. Responsive design expert.',
      'Builds component systems with CSS variables and animations.',
      'Architects CSS design systems. Deep browser rendering knowledge.',
      'Contributes to CSS frameworks. Browser compatibility expert.',
      'Author of major CSS tooling or design system libraries.',
      'Shapes CSS architecture at organizational and industry level.',
      'Core contributor to CSS working group or major frameworks.',
      'Among the most influential CSS practitioners globally.',
    ]),
  },
  {
    id: 'mobile_dev',
    name: 'Mobile Development',
    icon: '📱',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Has built or modified a simple mobile app.',
      'Builds mobile UIs with React Native, Flutter, or native SDKs.',
      'Handles navigation, state management, and device APIs.',
      'Builds production-quality mobile apps. App Store deployment.',
      'Architects complex mobile applications. Performance optimization.',
      'Deep platform knowledge (iOS/Android internals). Cross-platform expert.',
      'Contributes to React Native or Flutter. Author of popular packages.',
      'Shapes mobile development patterns and ecosystem.',
      'Core contributor to major mobile platforms or frameworks.',
      'Among the top mobile architects globally.',
    ]),
  },
  {
    id: 'web3',
    name: 'Web3 / Blockchain',
    icon: '⛓️',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands what blockchain and smart contracts are.',
      'Has deployed a basic smart contract with Hardhat or Foundry.',
      'Writes Solidity contracts. Understands EVM, gas, and token standards.',
      'Builds dApps with ethers.js/wagmi. Audits contracts for common bugs.',
      'Designs secure DeFi protocols. Deep EVM knowledge.',
      'Authors widely-used Solidity libraries. Cross-chain expertise.',
      'Protocol designer. Recognized security researcher.',
      'Shapes Web3 ecosystem standards.',
      'EIP author or core contributor to major protocols.',
      'Foundational contributor to blockchain infrastructure.',
    ]),
  },
  {
    id: 'data_structures',
    name: 'Data Structures & Algorithms',
    icon: '🧮',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Knows what arrays, linked lists, and hash maps are.',
      'Implements sorting algorithms. Understands Big-O basics.',
      'Uses trees, heaps, and graphs. Solves medium LeetCode problems.',
      'Designs efficient algorithms from scratch. Strong problem decomposition.',
      'Solves hard algorithmic problems. Deep complexity analysis.',
      'Teaches algorithms. Contributes to competitive programming.',
      'Competitive programming champion. Author of algorithm courses.',
      'Shapes how algorithms are taught and applied in industry.',
      'Recognized researcher in algorithms or combinatorics.',
      'Foundational contributor to algorithm theory.',
    ]),
  },
  {
    id: 'bash_scripting',
    name: 'Bash / Shell Scripting',
    icon: '💻',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Runs basic commands in a terminal.',
      'Writes scripts to automate simple tasks. Pipes and redirects.',
      'Uses loops, conditionals, and functions in shell scripts.',
      'Writes robust, portable shell scripts. Process management.',
      'Automates complex workflows. Deep POSIX knowledge.',
      'Shell tooling contributor. Author of widely-used shell utilities.',
      'Recognized shell/CLI tooling expert.',
      'Shapes shell scripting practices across large organizations.',
      'Core contributor to major shell implementations (bash, zsh, fish).',
      'Foundational contributor to Unix shell tooling.',
    ]),
  },

  // ── AI / ML ──────────────────────────────────────────────────────────────────

  {
    id: 'ml_fundamentals',
    name: 'ML Fundamentals',
    icon: '🧠',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Knows what supervised/unsupervised learning means.',
      'Trains simple models with scikit-learn. Understands train/test split.',
      'Implements gradient descent, regularization. Tunes hyperparameters.',
      'Builds and evaluates CNNs, RNNs. Understands loss functions deeply.',
      'Trains models on custom datasets. Strong evaluation methodology.',
      'Implements research papers from scratch. Expert in optimization theory.',
      'Publishes ML research. Deep expertise in multiple sub-domains.',
      'NeurIPS/ICML contributor. Recognized researcher.',
      'Lab director or principal researcher at top institution.',
      'Turing Award candidate. Foundational contributions to ML.',
    ]),
  },
  {
    id: 'deep_learning',
    name: 'Deep Learning',
    icon: '🔮',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands neural network basics — layers, activations, backprop.',
      'Trains simple neural nets with PyTorch or TensorFlow.',
      'Builds CNNs and RNNs for standard tasks. Understands batch norm.',
      'Implements transformers, attention mechanisms from papers.',
      'Pre-trains and fine-tunes large models. Advanced optimization.',
      'Authors novel architectures. Deep understanding of training dynamics.',
      'Published researcher at top venues. Foundational model trainer.',
      'Shapes the direction of deep learning research.',
      'Recognized as a seminal researcher in deep learning.',
      'Among the top 20 deep learning researchers globally.',
    ]),
  },
  {
    id: 'llm_engineering',
    name: 'LLM Engineering',
    icon: '✨',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Has used ChatGPT or similar tools.',
      'Calls OpenAI/Anthropic APIs with basic prompts. Knows temperature and tokens.',
      'Writes effective system prompts. Implements RAG with a vector DB.',
      'Builds multi-step LLM pipelines. Evaluates model outputs systematically.',
      'Fine-tunes models. Architects production LLM applications with evals.',
      'Trains custom models. Deep understanding of attention mechanisms.',
      'Contributes to open-source LLM tooling. Recognized in the LLM community.',
      'Architects frontier model training pipelines.',
      'Key contributor to foundational LLM research.',
      'Helped build GPT-4, Claude, or Gemini class models.',
    ]),
  },
  {
    id: 'prompt_engineering',
    name: 'Prompt Engineering',
    icon: '📝',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands that prompt wording affects AI output.',
      'Uses few-shot examples and basic chain-of-thought prompts.',
      'Designs system prompts for production use cases. Uses structured output.',
      'Builds reliable prompt pipelines. A/B tests prompts systematically.',
      'Deep expertise in prompt optimization. LLM evaluation frameworks.',
      'Designs prompt-based systems at scale. Red-teaming expertise.',
      'Recognized prompt engineering researcher or thought leader.',
      'Shapes how organizations use and evaluate AI systems.',
      'Author of seminal work on prompt engineering techniques.',
      'Foundational influence on the discipline of prompting and AI alignment.',
    ]),
  },
  {
    id: 'ai_agents',
    name: 'AI Agents',
    icon: '🤖',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands what autonomous AI agents are.',
      'Has used LangChain or similar to build a simple agent.',
      'Builds multi-step tool-using agents. Manages memory and state.',
      'Designs reliable agent pipelines with fallbacks and evals.',
      'Architects multi-agent systems. Deep understanding of agent safety.',
      'Author of agent frameworks or widely-used agent tooling.',
      'Recognized expert in autonomous agents. Speaker and researcher.',
      'Shapes agent architectures and safety practices at scale.',
      'Foundational researcher in agentic AI systems.',
      'Among the most influential AI agent architects globally.',
    ]),
  },
  {
    id: 'nlp',
    name: 'NLP',
    icon: '🗣️',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands tokenization, embeddings, and text classification basics.',
      'Uses spaCy or NLTK for text processing. Fine-tunes BERT.',
      'Builds NLP pipelines: NER, sentiment, summarization.',
      'Fine-tunes transformers for custom tasks. Understands attention.',
      'Designs production NLP systems. Evaluation and benchmarking.',
      'Contributes to HuggingFace. Deep multilingual expertise.',
      'Published NLP researcher. Author of widely-used NLP libraries.',
      'Shapes NLP field direction.',
      'Recognized as a leading NLP researcher globally.',
      'Foundational contributor to modern NLP.',
    ]),
  },
  {
    id: 'computer_vision',
    name: 'Computer Vision',
    icon: '👁️',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands image classification and convolutions.',
      'Uses torchvision or OpenCV for basic CV tasks.',
      'Implements object detection and segmentation models.',
      'Trains custom CV models from scratch. Transfer learning expertise.',
      'Deploys production CV systems. Real-time inference optimization.',
      'Designs novel CV architectures. Contributes to CV research.',
      'Published CV researcher at top venues.',
      'Shapes the direction of computer vision research.',
      'Recognized leading CV researcher.',
      'Foundational contributor to computer vision.',
    ]),
  },
  {
    id: 'reinforcement_learning',
    name: 'Reinforcement Learning',
    icon: '🎮',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands reward, policy, and agent-environment loops.',
      'Implements Q-learning and basic RL with OpenAI Gym.',
      'Implements policy gradient methods. Uses Stable Baselines.',
      'Designs custom RL environments. RLHF for LLM training.',
      'Trains RL agents for complex tasks. Deep understanding of exploration.',
      'Research-level RL. Contributes to RL frameworks.',
      'Published RL researcher. Author of RL algorithms.',
      'Shapes RL research direction.',
      'Leading RL researcher globally.',
      'Foundational contributor to reinforcement learning.',
    ]),
  },
  {
    id: 'mlops',
    name: 'MLOps',
    icon: '⚙️',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands the gap between notebooks and production ML.',
      'Uses MLflow or W&B for experiment tracking.',
      'Builds model serving with FastAPI or TorchServe. CI for ML.',
      'Designs full ML pipelines with feature stores and model registries.',
      'Operates production ML systems at scale. Drift detection.',
      'Architects ML platforms. Deep Kubeflow or Vertex AI expertise.',
      'MLOps thought leader. Author of MLOps tooling.',
      'Shapes how organizations build and operate ML systems.',
      'Recognized expert in production ML infrastructure.',
      'Foundational contributor to MLOps practices and tooling.',
    ]),
  },
  {
    id: 'statistics',
    name: 'Statistics & Probability',
    icon: '📈',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands mean, variance, and basic distributions.',
      'Applies hypothesis testing and confidence intervals.',
      'Uses Bayesian reasoning and regression analysis.',
      'Designs A/B tests. Deep understanding of statistical inference.',
      'Statistical modeling for production ML and experimentation platforms.',
      'Deep expertise in Bayesian methods or causal inference.',
      'Published statistician. Author of statistical methods.',
      'Shapes statistical thinking across data-driven organizations.',
      'Recognized leading statistician or probability theorist.',
      'Foundational contributor to statistical theory.',
    ]),
  },
  {
    id: 'data_science',
    name: 'Data Science',
    icon: '🔬',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Knows how to load a CSV and compute basic stats in pandas.',
      'Cleans data, visualizes with matplotlib/seaborn, builds simple models.',
      'Exploratory analysis, feature engineering, end-to-end modeling.',
      'Designs rigorous analyses. Strong statistical foundations.',
      'Leads data science teams and projects end-to-end.',
      'Deep expertise in experimentation and causal inference.',
      'Published data science researcher or recognized practitioner.',
      'Shapes data science practices at an organizational scale.',
      'Recognized leading data scientist globally.',
      'Foundational contributor to data science methodology.',
    ]),
  },
  {
    id: 'vector_databases',
    name: 'Vector Databases',
    icon: '🧲',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands embeddings and why similarity search matters.',
      'Has used Pinecone, Weaviate, or pgvector to store and query vectors.',
      'Builds RAG pipelines. Understands ANN algorithms (HNSW, IVF).',
      'Optimizes vector search at scale. Hybrid search strategies.',
      'Architects production vector infrastructure for large datasets.',
      'Deep understanding of vector indexing internals. Contributes to tooling.',
      'Recognized expert in vector search and embedding systems.',
      'Shapes vector database architecture and usage patterns.',
      'Core contributor to a major vector database project.',
      'Foundational researcher in approximate nearest neighbor search.',
    ]),
  },
  {
    id: 'pytorch',
    name: 'PyTorch / TensorFlow',
    icon: '🔥',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Has run a basic training loop in PyTorch or TensorFlow.',
      'Builds and trains simple neural networks. Understands tensors.',
      'Custom datasets, training loops, and model checkpointing.',
      'Advanced training techniques: mixed precision, gradient accumulation.',
      'Distributed training with DDP or FSDP. Large-scale training.',
      'Deep framework internals. Writes custom CUDA kernels.',
      'PyTorch/TF contributor. Author of widely-used training libraries.',
      'Shapes how frameworks are used and optimized in practice.',
      'Core contributor to PyTorch or TensorFlow.',
      'Foundational contributor to deep learning frameworks.',
    ]),
  },

  // ── Cloud / Infra ────────────────────────────────────────────────────────────

  {
    id: 'aws',
    name: 'AWS',
    icon: '☁️',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Has used the AWS console. Understands EC2 and S3 basics.',
      'Deploys apps on EC2 or Lambda. Uses S3, RDS, and IAM.',
      'Architects VPCs, load balancers, and auto-scaling groups.',
      'Designs multi-service AWS architectures. Cost optimization.',
      'AWS Solutions Architect Associate+ level. Multi-region deployments.',
      'AWS Advanced Networking. Deep security and compliance expertise.',
      'AWS Hero or Solutions Architect Professional. Author of tutorials.',
      'Shapes AWS usage patterns for large organizations.',
      'AWS Distinguished Engineer level. Contributes to AWS services.',
      'Among the most recognized AWS architects globally.',
    ]),
  },
  {
    id: 'gcp',
    name: 'GCP',
    icon: '🌐',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Has used GCP console. Understands Compute Engine and Cloud Storage.',
      'Deploys apps on GCP. Uses Cloud Run, BigQuery, and IAM.',
      'Architects VPCs and GKE clusters. Understands GCP networking.',
      'Designs multi-service GCP architectures. Cost optimization.',
      'GCP Professional level expertise. Multi-region deployments.',
      'Deep Vertex AI and data engineering on GCP.',
      'GCP Champion or recognized expert. Author of GCP content.',
      'Shapes GCP usage patterns for large organizations.',
      'Google Developer Expert or internal GCP architect.',
      'Foundational contributor to GCP services.',
    ]),
  },
  {
    id: 'azure',
    name: 'Azure',
    icon: '🔵',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Has used Azure portal. Understands VMs and Blob storage.',
      'Deploys apps on Azure App Service or Functions.',
      'Architects Azure Virtual Networks, AKS, and Azure AD.',
      'Designs multi-service Azure architectures with cost optimization.',
      'Azure Solutions Architect Expert level. Enterprise scenarios.',
      'Deep Azure DevOps and security architecture.',
      'Microsoft MVP or Azure expert. Author of Azure content.',
      'Shapes Azure adoption patterns for large organizations.',
      'Azure product team contributor level.',
      'Foundational contributor to Azure services.',
    ]),
  },
  {
    id: 'terraform',
    name: 'Terraform / IaC',
    icon: '🏗️',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands what Infrastructure as Code means.',
      'Writes basic Terraform configs. Plans and applies changes.',
      'Uses modules, variables, and remote state. Multi-environment setup.',
      'Designs reusable Terraform modules. State management best practices.',
      'Architects IaC for large organizations. CDK and Pulumi expertise.',
      'Deep Terraform internals. Contributes to providers.',
      'HashiCorp Ambassador or recognized IaC expert.',
      'Shapes IaC practices and tooling for large engineering orgs.',
      'Core contributor to Terraform or OpenTofu.',
      'Foundational contributor to Infrastructure as Code practices.',
    ]),
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    icon: '⎈',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands pods, deployments, and services.',
      'Deploys apps to Kubernetes. Uses kubectl for basic operations.',
      'Writes Helm charts. Configures ingress, RBAC, and config maps.',
      'Designs production K8s clusters. Networking and storage deep-dive.',
      'Architects multi-cluster K8s platforms. Operator pattern.',
      'Kubernetes internals. Contributes to operators and tools.',
      'CNCF Ambassador or recognized K8s expert.',
      'Shapes Kubernetes adoption and best practices at scale.',
      'Kubernetes core contributor.',
      'Foundational contributor to the Kubernetes ecosystem.',
    ]),
  },
  {
    id: 'ci_cd',
    name: 'CI/CD',
    icon: '🔄',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands what CI/CD is and why it matters.',
      'Sets up GitHub Actions or GitLab CI pipelines.',
      'Builds multi-stage pipelines with testing and deployment gates.',
      'Designs deployment strategies (blue-green, canary).',
      'Architects CI/CD platforms for engineering organizations.',
      'Deep expertise in deployment safety and rollback strategies.',
      'Author of CI/CD tooling or recognized DevOps expert.',
      'Shapes deployment practices across large engineering orgs.',
      'Core contributor to major CI/CD platforms.',
      'Foundational contributor to continuous delivery practices.',
    ]),
  },
  {
    id: 'monitoring',
    name: 'Monitoring & Observability',
    icon: '📡',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands logs, metrics, and traces.',
      'Sets up Datadog, Grafana, or CloudWatch dashboards.',
      'Designs alerting strategies. Uses structured logging.',
      'Builds observability stacks. SLO/SLA design.',
      'Architects observability platforms for complex distributed systems.',
      'Deep OpenTelemetry expertise. Chaos engineering.',
      'Author of monitoring tooling or recognized SRE expert.',
      'Shapes observability culture across large engineering orgs.',
      'Core contributor to observability standards (OpenTelemetry, etc.).',
      'Foundational contributor to site reliability engineering.',
    ]),
  },
  {
    id: 'security',
    name: 'Security',
    icon: '🔒',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands common vulnerabilities (OWASP Top 10).',
      'Implements HTTPS, auth, and basic input validation.',
      'Performs security reviews. Uses SAST/DAST tools.',
      'Threat modeling. Penetration testing fundamentals.',
      'Designs secure systems end-to-end. Incident response.',
      'Deep cryptography and identity expertise. Zero-trust architecture.',
      'Published security researcher. CVE reporter.',
      'Shapes security culture and practices at enterprise scale.',
      'Recognized leading security researcher.',
      'Foundational contributor to security standards or cryptography.',
    ]),
  },
  {
    id: 'serverless',
    name: 'Serverless',
    icon: '⚡',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands FaaS (Functions as a Service) concepts.',
      'Has deployed a Lambda or Cloud Function.',
      'Builds event-driven serverless architectures. Cold start management.',
      'Designs scalable serverless systems. Cost modeling.',
      'Architects complex serverless platforms. Edge computing.',
      'Deep expertise in serverless patterns and limitations.',
      'Author of serverless frameworks or recognized expert.',
      'Shapes serverless adoption patterns.',
      'Core contributor to serverless frameworks or platforms.',
      'Foundational contributor to serverless computing.',
    ]),
  },
  {
    id: 'linux',
    name: 'Linux',
    icon: '🐧',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Navigates the filesystem and runs basic commands.',
      'Manages users, permissions, and processes. Configures services.',
      'Writes system scripts. Manages packages and dependencies.',
      'Performance tuning. Kernel parameters and networking.',
      'Deep kernel knowledge. System security hardening.',
      'Kernel module development. Custom kernel builds.',
      'Linux kernel contributor or recognized system expert.',
      'Shapes Linux usage in large-scale infrastructure.',
      'Linux kernel maintainer or core contributor.',
      'Foundational contributor to the Linux kernel.',
    ]),
  },
  {
    id: 'networking',
    name: 'Networking',
    icon: '🌐',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands IP addresses, DNS, and HTTP.',
      'Configures firewalls, VPNs, and load balancers.',
      'Deep TCP/IP knowledge. BGP and routing protocols.',
      'Designs complex network topologies for cloud systems.',
      'Architects global networking infrastructure.',
      'Deep SDN and network security expertise.',
      'Author of networking tooling or recognized expert.',
      'Shapes networking architecture at enterprise scale.',
      'Core contributor to networking standards or protocols.',
      'Foundational contributor to Internet infrastructure.',
    ]),
  },
  {
    id: 'incident_response',
    name: 'Incident Response',
    icon: '🚨',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands what an incident is and how to report it.',
      'Can follow a runbook to respond to basic alerts.',
      'Leads incident response. Writes blameless post-mortems.',
      'Designs on-call rotations and escalation policies.',
      'Builds incident management culture. Chaos engineering.',
      'Designs org-wide SRE practices and incident frameworks.',
      'Recognized SRE or incident management thought leader.',
      'Shapes incident management practices across large orgs.',
      'Industry-recognized SRE expert. Author of SRE practices.',
      'Foundational contributor to Site Reliability Engineering.',
    ]),
  },

  // ── Data ─────────────────────────────────────────────────────────────────────

  {
    id: 'data_engineering',
    name: 'Data Engineering',
    icon: '🏭',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands what data pipelines are.',
      'Builds basic ETL pipelines with Python or SQL.',
      'Designs data pipelines with Airflow or Prefect.',
      'Builds production data platforms with data quality checks.',
      'Architects scalable data infrastructure. Stream and batch processing.',
      'Deep expertise in data mesh and data lakehouse patterns.',
      'Author of data engineering tooling or recognized expert.',
      'Shapes data engineering practices at organizational scale.',
      'Core contributor to major data engineering frameworks.',
      'Foundational contributor to data engineering practices.',
    ]),
  },
  {
    id: 'sql_analytics',
    name: 'SQL Analytics',
    icon: '🔍',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Writes basic queries to explore data.',
      'Uses aggregate functions and GROUP BY for analysis.',
      'Masters window functions, CTEs, and complex joins.',
      'Optimizes analytical queries in BigQuery or Snowflake.',
      'Designs data models for analytics (star schema, etc.).',
      'Deep expertise in query optimization and warehouse internals.',
      'Author of analytics frameworks or recognized SQL expert.',
      'Shapes analytics practices across large data teams.',
      'Core contributor to analytics databases or SQL tooling.',
      'Foundational contributor to analytical query processing.',
    ]),
  },
  {
    id: 'data_visualization',
    name: 'Data Visualization',
    icon: '📊',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Creates basic charts in Excel or Google Sheets.',
      'Builds dashboards with Tableau, Looker, or Metabase.',
      'Designs clear, insightful visualizations. Knows Tufte principles.',
      'Builds interactive visualizations with D3.js or Observable.',
      'Designs data storytelling for executive audiences.',
      'Deep expertise in perceptual data visualization design.',
      'Author of visualization tooling or recognized expert.',
      'Shapes data visualization practices across organizations.',
      'Core contributor to D3.js or major BI platforms.',
      'Foundational contributor to data visualization theory.',
    ]),
  },
  {
    id: 'dbt',
    name: 'dbt',
    icon: '🔧',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands what dbt is and why it matters for analytics.',
      'Writes basic dbt models and tests.',
      'Uses dbt macros, sources, and documentation.',
      'Designs modular dbt projects with proper layer architecture.',
      'Architects large dbt projects. Performance optimization.',
      'Deep dbt internals. Contributes to dbt packages.',
      'Author of dbt packages or recognized dbt expert.',
      'Shapes dbt practices across data teams.',
      'Core contributor to dbt-core.',
      'Foundational contributor to the analytics engineering movement.',
    ]),
  },
  {
    id: 'spark',
    name: 'Apache Spark',
    icon: '⚡',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands distributed computing concepts.',
      'Runs basic Spark jobs with PySpark.',
      'Uses DataFrames, Spark SQL, and joins at scale.',
      'Optimizes Spark jobs. Understands partitioning and shuffles.',
      'Architects Spark-based data platforms.',
      'Deep Spark internals. Streaming with Spark Structured Streaming.',
      'Author of Spark libraries or recognized expert.',
      'Shapes big data architecture across large organizations.',
      'Apache Spark committer or PMC member.',
      'Foundational contributor to distributed data processing.',
    ]),
  },
  {
    id: 'kafka',
    name: 'Apache Kafka',
    icon: '📨',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands message queues and pub/sub patterns.',
      'Produces and consumes messages with Kafka.',
      'Designs Kafka topics, partitions, and consumer groups.',
      'Builds event-driven architectures with Kafka Streams.',
      'Operates Kafka clusters. Replication and availability.',
      'Deep Kafka internals. Schema registry and compaction.',
      'Author of Kafka tooling or recognized stream processing expert.',
      'Shapes event-driven architecture patterns at scale.',
      'Apache Kafka committer or PMC member.',
      'Foundational contributor to distributed messaging systems.',
    ]),
  },
  {
    id: 'data_warehousing',
    name: 'Data Warehousing',
    icon: '🏢',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands what a data warehouse is.',
      'Uses Snowflake or BigQuery to query data.',
      'Designs warehouse schemas. Understands star and snowflake schemas.',
      'Optimizes warehouse performance and costs.',
      'Architects enterprise data warehouse strategies.',
      'Deep expertise in modern data stack (lakehouse, etc.).',
      'Author of data warehouse tooling or recognized expert.',
      'Shapes data architecture strategy for large organizations.',
      'Core contributor to major data warehouse platforms.',
      'Foundational contributor to data warehousing technology.',
    ]),
  },
  {
    id: 'feature_engineering',
    name: 'Feature Engineering',
    icon: '⚗️',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands what features are in ML.',
      'Creates basic features from raw data for ML models.',
      'Engineers domain-specific features. Handles missing data.',
      'Designs feature stores. Automated feature engineering.',
      'Architects feature platforms for production ML.',
      'Deep expertise in temporal features and leakage prevention.',
      'Author of feature engineering tooling or recognized expert.',
      'Shapes feature engineering practices across ML platforms.',
      'Core contributor to feature store platforms.',
      'Foundational contributor to feature engineering methodology.',
    ]),
  },
  {
    id: 'excel_analytics',
    name: 'Excel / Sheets',
    icon: '📋',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Uses basic formulas (SUM, AVERAGE, IF).',
      'Builds pivot tables and basic charts.',
      'Uses VLOOKUP/INDEX-MATCH, array formulas, and macros.',
      'Builds complex financial models and dashboards.',
      'Designs advanced Excel tooling for non-technical stakeholders.',
      'Excel MVP-level expertise. VBA and Power Query mastery.',
      'Recognized Excel expert. Author of templates and courses.',
      'Shapes how organizations use spreadsheets for analysis.',
      'Microsoft MVP or community leader in spreadsheet analytics.',
      'Foundational influence on spreadsheet analytics practices.',
    ]),
  },
  {
    id: 'analytics_engineering',
    name: 'Analytics Engineering',
    icon: '🔭',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands the analytics engineer role bridging data and business.',
      'Writes clean SQL and builds basic dbt models.',
      'Designs data marts and self-serve analytics layers.',
      'Owns the semantic layer for a product or company.',
      'Architects end-to-end analytics workflows.',
      'Deep expertise in metrics layers and semantic modeling.',
      'Recognized analytics engineering thought leader.',
      'Shapes how data teams build analytics products.',
      'Core contributor to analytics engineering frameworks.',
      'Foundational contributor to the analytics engineering discipline.',
    ]),
  },

  // ── Product ──────────────────────────────────────────────────────────────────

  {
    id: 'product_management',
    name: 'Product Management',
    icon: '🎯',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Understands the role of a PM. Can write a basic user story.',
      'Writes PRDs. Conducts user interviews. Manages a basic backlog.',
      'Defines product strategy. Uses data to prioritize features.',
      'Drives 0-to-1 products. Runs A/B tests. Strong stakeholder management.',
      'Leads product teams for complex, high-growth products.',
      'Sets product vision and multi-year roadmaps.',
      'CPO-level strategic thinking. Builds PM orgs.',
      'Built multiple breakout products. Recognized industry leader.',
      'Advises top-tier startups. Thought leader with public body of work.',
      'Invented the iPhone, Gmail, or equivalent.',
    ]),
  },
  {
    id: 'user_research',
    name: 'User Research',
    icon: '🔎',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Has conducted a user interview or survey.',
      'Plans and runs usability tests. Synthesizes findings.',
      'Uses mixed methods: interviews, surveys, and analytics.',
      'Designs research programs. Builds user panels.',
      'Leads research for complex products. Generative and evaluative research.',
      'Deep expertise in behavioral research and ethnography.',
      'Author of research methods or recognized UXR expert.',
      'Shapes how organizations use research to drive decisions.',
      'Recognized leading researcher in human-computer interaction.',
      'Foundational contributor to user research methodology.',
    ]),
  },
  {
    id: 'growth',
    name: 'Growth',
    icon: '📈',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Understands acquisition funnels and basic growth metrics.',
      'Runs basic growth experiments. Understands CAC and LTV.',
      'Designs A/B tests. Uses analytics to identify growth levers.',
      'Leads growth teams. Viral loops and referral mechanics.',
      'Architects growth platforms for high-scale products.',
      'Deep expertise in PLG, viral growth, and retention.',
      'Author of growth playbooks or recognized growth leader.',
      'Shapes growth practices across organizations.',
      'Recognized leading growth practitioner globally.',
      'Foundational contributor to growth methodology.',
    ]),
  },
  {
    id: 'product_analytics',
    name: 'Product Analytics',
    icon: '📉',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Understands DAU/MAU, retention, and conversion.',
      'Uses Mixpanel, Amplitude, or GA to analyze user behavior.',
      'Designs event taxonomies and funnel analyses.',
      'Builds self-serve analytics for product teams.',
      'Architects product analytics strategy. Experimentation platforms.',
      'Deep statistical expertise for product decisions.',
      'Author of analytics frameworks or recognized expert.',
      'Shapes how organizations use data to build products.',
      'Recognized leading product analytics practitioner.',
      'Foundational contributor to product analytics methodology.',
    ]),
  },
  {
    id: 'go_to_market',
    name: 'Go-to-Market',
    icon: '🚀',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Understands what a GTM strategy is.',
      'Has helped launch a feature or product.',
      'Coordinates launches across product, marketing, and sales.',
      'Leads GTM for new product lines.',
      'Architects GTM strategy for platform or marketplace products.',
      'Deep enterprise GTM and pricing strategy expertise.',
      'Author of GTM playbooks or recognized expert.',
      'Shapes GTM practices for large product organizations.',
      'Recognized leading GTM strategist.',
      'Foundational contributor to product launch methodology.',
    ]),
  },
  {
    id: 'pricing_strategy',
    name: 'Pricing Strategy',
    icon: '💰',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Understands freemium, subscription, and usage-based models.',
      'Has contributed to pricing decisions with data.',
      'Designs pricing tiers and packaging experiments.',
      'Leads pricing strategy for a product line.',
      'Architects pricing for complex platform businesses.',
      'Deep value-based pricing and willingness-to-pay research.',
      'Author of pricing frameworks or recognized expert.',
      'Shapes monetization strategy for large organizations.',
      'Recognized leading pricing strategist.',
      'Foundational contributor to software pricing methodology.',
    ]),
  },
  {
    id: 'agile',
    name: 'Agile / Scrum',
    icon: '🔄',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Has participated in sprint ceremonies.',
      'Runs sprint planning, standups, and retrospectives.',
      'Coaches teams on agile practices. Removes blockers effectively.',
      'Leads agile transformations within teams.',
      'Designs agile practices for large engineering organizations.',
      'Deep SAFe and scaled agile expertise.',
      'Author of agile content or recognized agile coach.',
      'Shapes agile practices across large organizations.',
      'Recognized leading agile practitioner.',
      'Foundational contributor to agile methodology.',
    ]),
  },
  {
    id: 'okrs',
    name: 'OKRs & Strategy',
    icon: '🏆',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Understands OKRs and how they cascade from company to team.',
      'Writes team-level OKRs aligned to company goals.',
      'Facilitates OKR setting and quarterly reviews.',
      'Designs OKR programs for product organizations.',
      'Architects strategic planning processes for companies.',
      'Deep expertise in strategy frameworks (BCG, Porter, etc.).',
      'Author of strategy frameworks or recognized thought leader.',
      'Shapes how organizations set and execute on strategy.',
      'Recognized leading strategy practitioner.',
      'Foundational contributor to business strategy methodology.',
    ]),
  },
  {
    id: 'competitive_analysis',
    name: 'Competitive Analysis',
    icon: '🔭',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Can name competitors and basic differentiators.',
      'Conducts structured competitive research.',
      'Designs competitive intelligence programs.',
      'Uses competitive insights to drive product decisions.',
      'Leads competitive strategy for market positioning.',
      'Deep market analysis and category creation expertise.',
      'Author of market analysis frameworks or recognized expert.',
      'Shapes competitive strategy across large organizations.',
      'Recognized leading market analyst or strategist.',
      'Foundational contributor to competitive strategy methodology.',
    ]),
  },

  // ── Design ───────────────────────────────────────────────────────────────────

  {
    id: 'ux_design',
    name: 'UX Design',
    icon: '🧩',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Understands basic UX principles. Can critique a UI.',
      'Creates wireframes in Figma. Runs basic usability tests.',
      'Designs complete user flows. Uses design systems effectively.',
      'Leads end-to-end design for a product feature. Builds design systems.',
      'Owns product design strategy. Deep research capabilities.',
      'Designs experiences for millions of users. Strong systems thinking.',
      'Head of Design caliber. Shapes design culture.',
      'Designs products that define their categories.',
      'Industry design luminary. Speaker, author, or advisor.',
      'Dieter Rams or Jony Ive tier. Legacy design work.',
    ]),
  },
  {
    id: 'ui_design',
    name: 'UI Design',
    icon: '🖥️',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Can identify good vs. bad UI. Understands visual hierarchy.',
      'Designs screens and components in Figma. Uses existing design systems.',
      'Creates polished, consistent UIs. Responsive layouts.',
      'Designs complex interfaces for web and mobile.',
      'Owns UI quality for a product. Builds component libraries.',
      'Deep visual design expertise. High-fidelity prototyping.',
      'Author of design systems used by large teams.',
      'Shapes UI quality standards across products.',
      'Recognized leading UI designer globally.',
      'Foundational contributor to UI design language.',
    ]),
  },
  {
    id: 'figma',
    name: 'Figma',
    icon: '🔲',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Can open and view a Figma file. Makes basic edits.',
      'Creates frames, components, and auto-layouts.',
      'Uses variables, interactive components, and prototyping.',
      'Builds large component libraries. Advanced Figma workflows.',
      'Designs at enterprise scale in Figma. Plugin development.',
      'Figma plugin author or expert trainer.',
      'Recognized Figma expert. Author of popular templates.',
      'Shapes how teams use Figma for design systems.',
      'Figma community leader or early plugin ecosystem builder.',
      'Foundational contributor to the Figma ecosystem.',
    ]),
  },
  {
    id: 'design_systems',
    name: 'Design Systems',
    icon: '🏛️',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Understands what a design system is.',
      'Uses an existing design system (Material, Radix, etc.).',
      'Contributes to a design system. Documents components.',
      'Leads design system development for a product.',
      'Architects design systems for large organizations.',
      'Deep token architecture and cross-platform design systems.',
      'Author of widely-used design systems or tooling.',
      'Shapes design system practices across the industry.',
      'Recognized leading design systems practitioner.',
      'Foundational contributor to design systems methodology.',
    ]),
  },
  {
    id: 'brand_design',
    name: 'Brand Design',
    icon: '✏️',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Understands brand identity basics: logo, colors, typography.',
      'Applies brand guidelines consistently.',
      'Designs brand assets: icons, illustrations, marketing materials.',
      'Leads brand identity projects for startups.',
      'Develops comprehensive brand systems for growing companies.',
      'Designs brand identities for public companies or global brands.',
      'Recognized brand designer. Speaker and thought leader.',
      'Shapes brand strategy and visual identity at scale.',
      'Recognized leading brand designer globally.',
      'Defined iconic brand identities.',
    ]),
  },
  {
    id: 'motion_design',
    name: 'Motion Design',
    icon: '🎬',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Understands animation basics: keyframes and timing.',
      'Creates simple UI animations with CSS or Framer Motion.',
      'Designs polished micro-interactions and transitions.',
      'Leads motion design for product UIs.',
      'Architects motion systems for design systems.',
      'Deep expertise in complex motion and 3D animation.',
      'Author of motion design tooling or recognized expert.',
      'Shapes motion design practices at product companies.',
      'Recognized leading motion designer globally.',
      'Foundational contributor to UI motion design language.',
    ]),
  },
  {
    id: 'accessibility',
    name: 'Accessibility',
    icon: '♿',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Understands what accessibility means and why it matters.',
      'Checks color contrast and adds alt text.',
      'Implements WCAG 2.1 AA across a product. Keyboard navigation.',
      'Leads accessibility audits and remediation programs.',
      'Designs accessible-first design systems.',
      'Deep WCAG AAA, ARIA, and assistive technology expertise.',
      'Author of accessibility tooling or recognized expert.',
      'Shapes accessibility culture across organizations.',
      'Recognized leading accessibility practitioner.',
      'Foundational contributor to accessibility standards.',
    ]),
  },
  {
    id: 'visual_design',
    name: 'Visual Design',
    icon: '🖌️',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Understands color, typography, and layout basics.',
      'Creates visually pleasing designs using design principles.',
      'Masters grid systems, typographic hierarchy, and color theory.',
      'Designs high-impact marketing and product visuals.',
      'Leads visual design for large-scale products.',
      'Deep expertise in editorial and print design traditions.',
      'Author of visual design resources or recognized expert.',
      'Shapes visual design language for large organizations.',
      'Recognized leading visual designer globally.',
      'Foundational contributor to visual design methodology.',
    ]),
  },
  {
    id: 'interaction_design',
    name: 'Interaction Design',
    icon: '🖱️',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Understands user interactions and basic affordances.',
      'Maps user flows and designs basic interactions.',
      'Designs complex multi-step interactions with edge cases.',
      'Leads interaction design for complex product domains.',
      'Architects interaction patterns for large-scale products.',
      'Deep expertise in gesture, voice, and emerging input modalities.',
      'Author of interaction design patterns or recognized expert.',
      'Shapes interaction design practices at industry level.',
      'Recognized leading interaction designer globally.',
      'Foundational contributor to interaction design theory.',
    ]),
  },

  // ── Engineering (additional) ─────────────────────────────────────────────────

  {
    id: 'c_sharp',
    name: 'C# / .NET',
    icon: '🟣',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands C# syntax and basic OOP.',
      'Builds .NET applications with ASP.NET Core.',
      'Uses LINQ, async/await, and Entity Framework.',
      'Designs production .NET services. Deep CLR knowledge.',
      'Architects enterprise .NET systems. Performance tuning.',
      'Deep .NET internals. Roslyn compiler knowledge.',
      'Author of .NET libraries or recognized community expert.',
      'Shapes .NET ecosystem and enterprise architecture patterns.',
      '.NET core contributor or Microsoft MVP.',
      'Foundational contributor to the .NET platform.',
    ]),
  },
  {
    id: 'svelte',
    name: 'Svelte / SvelteKit',
    icon: '🔶',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands how Svelte differs from React. Reads Svelte code.',
      'Builds basic Svelte apps. Uses stores and reactivity.',
      'Uses SvelteKit for SSR. Manages routing and data loading.',
      'Builds production Svelte apps. Advanced animations.',
      'Architects large SvelteKit applications. Performance mastery.',
      'Deep Svelte compiler knowledge. Contributes to ecosystem.',
      'Author of Svelte libraries or recognized community expert.',
      'Shapes Svelte ecosystem and patterns.',
      'Svelte core contributor.',
      'Foundational contributor to the Svelte framework.',
    ]),
  },
  {
    id: 'php',
    name: 'PHP / Laravel',
    icon: '🐘',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Can read and modify basic PHP scripts.',
      'Builds web apps with Laravel. Understands MVC.',
      'Uses Eloquent, queues, and Blade templates.',
      'Builds production PHP services. Performance optimization.',
      'Architects large-scale PHP systems.',
      'Deep PHP internals. Contributes to PHP ecosystem.',
      'PHP core contributor or author of major Laravel packages.',
      'Shapes PHP ecosystem and practices.',
      'PHP core team member or Laravel core contributor.',
      'Foundational contributor to the PHP language.',
    ]),
  },
  {
    id: 'webassembly',
    name: 'WebAssembly',
    icon: '🕸️',
    branch: 'engineering',
    maxLevel: 10,
    levels: levels([
      'Understands what WebAssembly is and when to use it.',
      'Has compiled code to WASM and run it in a browser.',
      'Uses WASM with JavaScript interop. Wasm-pack for Rust.',
      'Builds high-performance WASM modules for production.',
      'Architects WASM-based applications. WASI and serverless.',
      'Deep WASM runtime internals. Contributes to tooling.',
      'Author of WASM tooling or recognized community expert.',
      'Shapes WebAssembly adoption patterns.',
      'W3C WebAssembly working group contributor.',
      'Foundational contributor to the WebAssembly specification.',
    ]),
  },

  // ── Cloud / Infra (additional) ───────────────────────────────────────────────

  {
    id: 'database_admin',
    name: 'Database Administration',
    icon: '💾',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands basic DB administration concepts.',
      'Manages PostgreSQL or MySQL instances. Backup and restore.',
      'Configures replication, connection pooling, and maintenance.',
      'Performance tunes databases. Vacuum, analyze, index strategies.',
      'Operates databases at scale. High availability configurations.',
      'Deep DB engine internals. Multi-region failover expertise.',
      'Author of DBA tooling or recognized database expert.',
      'Shapes database operations for large organizations.',
      'Core contributor to a major open-source database.',
      'Foundational contributor to database engine development.',
    ]),
  },

  // ── Data (additional) ────────────────────────────────────────────────────────

  {
    id: 'r_programming',
    name: 'R',
    icon: '📊',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands R syntax. Can run a basic analysis.',
      'Uses tidyverse for data manipulation and ggplot2 for charts.',
      'Builds statistical models in R. Reproducible research with R Markdown.',
      'Writes production R code. Shiny apps for interactive analysis.',
      'Designs R packages. Deep statistical programming expertise.',
      'CRAN package author. Deep bioinformatics or econometrics.',
      'Author of widely-used R packages or recognized expert.',
      'Shapes how R is used in data science and research.',
      'R core contributor or recognized R community leader.',
      'Foundational contributor to the R language or ecosystem.',
    ]),
  },
  {
    id: 'time_series',
    name: 'Time Series Analysis',
    icon: '📉',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands time series data and its unique challenges.',
      'Applies basic forecasting (moving averages, ARIMA).',
      'Uses Prophet or statsmodels for forecasting. Seasonality handling.',
      'Builds production forecasting systems. Anomaly detection.',
      'Architects time series platforms at scale.',
      'Deep expertise in temporal modeling and Bayesian forecasting.',
      'Author of time series libraries or recognized expert.',
      'Shapes how organizations do forecasting and monitoring.',
      'Recognized leading time series researcher.',
      'Foundational contributor to time series methodology.',
    ]),
  },

  // ── Product (additional) ─────────────────────────────────────────────────────

  {
    id: 'customer_success',
    name: 'Customer Success',
    icon: '🤝',
    branch: 'product',
    maxLevel: 10,
    levels: levels([
      'Understands customer success role and churn prevention basics.',
      'Manages customer onboarding and support tickets.',
      'Builds playbooks and health scoring for customer accounts.',
      'Leads customer success for enterprise accounts.',
      'Designs CS organization and processes from scratch.',
      'Architects customer success programs at scale. Expansion revenue.',
      'Author of CS frameworks or recognized community expert.',
      'Shapes customer success practices across organizations.',
      'Recognized leading CS practitioner globally.',
      'Foundational contributor to customer success methodology.',
    ]),
  },

  // ── Design (additional) ──────────────────────────────────────────────────────

  {
    id: 'illustration',
    name: 'Illustration',
    icon: '🖼️',
    branch: 'design',
    maxLevel: 10,
    levels: levels([
      'Can sketch basic shapes and concepts.',
      'Creates simple digital illustrations with Illustrator or Procreate.',
      'Develops consistent illustration styles for UI use.',
      'Leads illustration direction for a product or brand.',
      'Designs illustration systems with full style guides.',
      'Deep expertise in narrative illustration and complex scenes.',
      'Author of illustration resources or recognized expert.',
      'Shapes illustration aesthetics in the tech industry.',
      'Recognized leading illustrator globally.',
      'Foundational influence on digital illustration style.',
    ]),
  },

  // ── Soft Skills ──────────────────────────────────────────────────────────────

  {
    id: 'communication',
    name: 'Communication',
    icon: '💬',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Can express ideas verbally in a team setting.',
      'Writes clear emails and Slack messages. Structures arguments.',
      'Presents confidently to small teams. Tailors message to audience.',
      'Persuades and influences. Navigates difficult conversations well.',
      'Presents to executives or large audiences with impact.',
      'Shapes organizational narratives. High-stakes communication expert.',
      'Conference keynote quality. Published author or speaker.',
      'Communication that moves industries or large communities.',
      'TED-tier communicator. Books with measurable cultural impact.',
      'Communication that shapes history.',
    ]),
  },
  {
    id: 'leadership',
    name: 'Leadership',
    icon: '👑',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Understands leadership styles and principles.',
      'Leads small projects or initiatives. Reliable team contributor.',
      'Leads a team. Sets direction and removes blockers.',
      'Builds high-performing teams. Coaches individuals effectively.',
      'Leads large engineering or product organizations.',
      'Shapes organizational culture and strategy.',
      'Executive-level leadership. Recognized thought leader.',
      'CEO/CTO caliber. Builds companies.',
      'Serial founder or legendary organizational builder.',
      'Leadership that shapes industries or movements.',
    ]),
  },
  {
    id: 'mentoring',
    name: 'Mentoring',
    icon: '🧑‍🏫',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Willing to help teammates with questions.',
      'Provides helpful feedback on code or work.',
      'Structured mentorship relationships. Career coaching.',
      'Builds mentorship programs within teams.',
      'Leads org-wide mentorship and career development programs.',
      'Executive coaching and organizational development expertise.',
      'Recognized coach or mentor. Author of mentoring frameworks.',
      'Shapes talent development practices at scale.',
      'Recognized leading executive coach or organizational developer.',
      'Foundational influence on mentoring and coaching methodology.',
    ]),
  },
  {
    id: 'negotiation',
    name: 'Negotiation',
    icon: '🤝',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Understands win-win negotiation basics.',
      'Negotiates effectively in everyday work situations.',
      'Uses principled negotiation (BATNA, interests vs. positions).',
      'Negotiates contracts and partnerships effectively.',
      'Leads high-stakes commercial negotiations.',
      'Deep M&A and complex deal negotiation expertise.',
      'Recognized negotiation trainer or author.',
      'Shapes negotiation practices across organizations.',
      'Author of widely-used negotiation methodology.',
      'Foundational contributor to negotiation theory.',
    ]),
  },
  {
    id: 'problem_solving',
    name: 'Problem Solving',
    icon: '🧩',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Can work through simple problems with guidance.',
      'Structures problems and identifies root causes independently.',
      'Applies systematic frameworks (5 Whys, MECE, etc.).',
      'Solves complex, ambiguous problems under pressure.',
      'Leads problem-solving for major organizational challenges.',
      'Deep expertise in systems thinking and complexity.',
      'Author of problem-solving frameworks or recognized expert.',
      'Shapes problem-solving culture across organizations.',
      'Recognized leading practitioner in systems thinking.',
      'Foundational contributor to problem-solving methodology.',
    ]),
  },
  {
    id: 'critical_thinking',
    name: 'Critical Thinking',
    icon: '🧐',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Questions assumptions when prompted.',
      'Identifies logical fallacies and evaluates evidence.',
      'Applies structured thinking to complex decisions.',
      'Leads high-stakes decision-making. Strong analytical rigor.',
      'Designs decision frameworks for organizations.',
      'Deep expertise in epistemology and cognitive bias.',
      'Author of critical thinking frameworks. Recognized thinker.',
      'Shapes how organizations make high-quality decisions.',
      'Recognized leading critical thinker or rationalist.',
      'Foundational contributor to epistemology or decision theory.',
    ]),
  },
  {
    id: 'technical_writing',
    name: 'Technical Writing',
    icon: '📄',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Can write clear code comments and basic documentation.',
      'Writes user-facing docs and READMEs.',
      'Designs comprehensive documentation for complex systems.',
      'Leads documentation strategy for a product or platform.',
      'Architects documentation systems at organizational scale.',
      'Deep expertise in docs-as-code and content strategy.',
      'Author of technical writing guides or recognized expert.',
      'Shapes how engineering orgs approach documentation.',
      'Recognized leading technical writer or content strategist.',
      'Foundational contributor to technical communication standards.',
    ]),
  },
  {
    id: 'public_speaking',
    name: 'Public Speaking',
    icon: '🎤',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Can speak briefly in a meeting without panic.',
      'Presents to teams and stakeholders with some confidence.',
      'Delivers polished presentations. Handles Q&A confidently.',
      'Presents at meetups or internal company events.',
      'Conference speaker. Keynotes at mid-sized events.',
      'TED/TEDx or major tech conference keynote.',
      'Recognized conference speaker and thought leader.',
      'Shapes ideas that spread widely through speaking.',
      'One of the most sought-after speakers in their domain.',
      'Speaker whose ideas define a generation.',
    ]),
  },
  {
    id: 'emotional_intelligence',
    name: 'Emotional Intelligence',
    icon: '💛',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Aware of own emotions and their impact.',
      'Manages emotions under pressure. Shows empathy.',
      'Reads team dynamics well. Navigates interpersonal tension.',
      'Builds psychologically safe environments. Conflict resolution.',
      'Leads with high EQ in complex organizational dynamics.',
      'Executive-level emotional and social intelligence.',
      'Author of EQ frameworks or recognized expert.',
      'Shapes team culture and emotional health at scale.',
      'Recognized leading practitioner in emotional intelligence.',
      'Foundational contributor to EQ theory and practice.',
    ]),
  },
  {
    id: 'project_management',
    name: 'Project Management',
    icon: '📅',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Tracks tasks and meets deadlines for their own work.',
      'Coordinates small projects across teams.',
      'Manages complex projects with dependencies. Risk management.',
      'Leads large cross-functional projects to delivery.',
      'Designs project management systems for organizations.',
      'Program management at enterprise scale. PMO design.',
      'Author of PM frameworks or recognized expert.',
      'Shapes project management culture across organizations.',
      'Recognized leading project management practitioner.',
      'Foundational contributor to project management methodology.',
    ]),
  },
  {
    id: 'strategic_thinking',
    name: 'Strategic Thinking',
    icon: '♟️',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Understands company goals and how their work connects.',
      'Contributes to team strategy discussions.',
      'Develops team and product strategies.',
      'Leads functional strategy (engineering, product, etc.).',
      'Develops company-level strategy.',
      'Deep expertise in competitive strategy and market dynamics.',
      'Author of strategy frameworks or recognized thought leader.',
      'Shapes strategic direction for large organizations.',
      'Recognized leading strategist.',
      'Foundational contributor to strategic thinking methodology.',
    ]),
  },
  {
    id: 'hiring',
    name: 'Hiring',
    icon: '🧑‍💼',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Has participated in an interview loop.',
      'Conducts structured technical interviews.',
      'Designs interview processes and assessment criteria.',
      'Leads hiring for a team. Talent sourcing and employer branding.',
      'Builds hiring programs for engineering orgs.',
      'Designs recruiting systems at scale. Diversity and inclusion.',
      'Author of hiring frameworks or recognized talent expert.',
      'Shapes hiring culture across large organizations.',
      'Recognized leading talent acquisition practitioner.',
      'Foundational contributor to hiring and talent methodology.',
    ]),
  },
  {
    id: 'time_management',
    name: 'Time Management',
    icon: '⏰',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Meets deadlines for their own tasks.',
      'Prioritizes effectively. Uses a personal productivity system.',
      'Manages multiple workstreams without dropping balls.',
      'Leads teams that consistently deliver on time.',
      'Designs time management systems for organizations.',
      'Deep expertise in productivity science and async work.',
      'Author of productivity frameworks or recognized expert.',
      'Shapes how organizations think about time and focus.',
      'Recognized leading productivity researcher or practitioner.',
      'Foundational contributor to time management methodology.',
    ]),
  },
  {
    id: 'resilience',
    name: 'Resilience',
    icon: '💪',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Can handle minor setbacks without derailing.',
      'Recovers from failures and learns from mistakes.',
      'Maintains performance under sustained pressure.',
      'Leads teams through crises and pivots.',
      'Builds resilient organizations that thrive in adversity.',
      'Deep expertise in organizational resilience and anti-fragility.',
      'Author of resilience frameworks or recognized expert.',
      'Shapes how organizations build resilience at scale.',
      'Recognized leading resilience practitioner.',
      'Foundational contributor to organizational resilience theory.',
    ]),
  },
  {
    id: 'ai_ethics',
    name: 'AI Ethics',
    icon: '⚖️',
    branch: 'ai_ml',
    maxLevel: 10,
    levels: levels([
      'Understands AI bias and fairness at a conceptual level.',
      'Identifies potential harms in AI systems. Follows responsible AI guidelines.',
      'Conducts model audits and bias evaluations.',
      'Designs responsible AI frameworks for products.',
      'Leads AI ethics programs for organizations.',
      'Deep expertise in fairness metrics, privacy, and accountability.',
      'Author of AI ethics guidelines or recognized researcher.',
      'Shapes AI ethics policy at industry or regulatory level.',
      'Recognized leading AI ethics researcher or practitioner.',
      'Foundational contributor to AI ethics standards globally.',
    ]),
  },
  {
    id: 'devops',
    name: 'DevOps',
    icon: '🔧',
    branch: 'cloud_infra',
    maxLevel: 10,
    levels: levels([
      'Understands DevOps culture and the SDLC.',
      'Automates deployments with basic CI/CD pipelines.',
      'Manages infrastructure as code. Implements shift-left testing.',
      'Designs DevOps practices for engineering teams.',
      'Leads DevOps transformation for organizations.',
      'Deep platform engineering and developer experience expertise.',
      'Author of DevOps tooling or recognized thought leader.',
      'Shapes how organizations build and operate software.',
      'Recognized leading DevOps practitioner globally.',
      'Foundational contributor to DevOps methodology.',
    ]),
  },
  {
    id: 'data_quality',
    name: 'Data Quality',
    icon: '✔️',
    branch: 'data',
    maxLevel: 10,
    levels: levels([
      'Understands what data quality means: accuracy, completeness.',
      'Writes basic data validation checks in SQL or Python.',
      'Uses Great Expectations or dbt tests for data pipelines.',
      'Designs data quality frameworks for production pipelines.',
      'Leads data quality strategy for data platforms.',
      'Deep expertise in data observability and anomaly detection.',
      'Author of data quality tooling or recognized expert.',
      'Shapes how organizations think about data reliability.',
      'Recognized leading data quality practitioner.',
      'Foundational contributor to data quality methodology.',
    ]),
  },
  {
    id: 'sales',
    name: 'Sales',
    icon: '💼',
    branch: 'soft_skills',
    maxLevel: 10,
    levels: levels([
      'Understands basic sales concepts: pipeline, funnel, close.',
      'Qualifies leads and conducts discovery calls.',
      'Runs full sales cycles. Negotiates and closes deals.',
      'Builds and exceeds quota. Account expansion.',
      'Leads sales teams. Designs compensation and process.',
      'Deep enterprise sales and complex deal management.',
      'Author of sales playbooks or recognized sales leader.',
      'Shapes go-to-market and sales culture at organizations.',
      'Recognized leading sales practitioner or author.',
      'Foundational contributor to modern B2B sales methodology.',
    ]),
  },
];

// ---------- Seed Profiles ----------

export const SEED_PROFILES: Profile[] = [
  {
    username: 'alex',
    displayName: 'Alex Chen',
    bio: 'Full-stack engineer. Building the future of human-AI collaboration. Previously Stripe.',
    avatarEmoji: '👩‍💻',
    entityType: 'human',
    privacy: 'public',
    totalXp: 8420,
    skills: [
      {
        skillId: 'typescript',
        currentLevel: 7,
        xp: 2500,
        evidence: [
          { type: 'contribution', title: 'DefinitelyTyped contributor (42 merged PRs)', url: 'https://github.com/DefinitelyTyped/DefinitelyTyped' },
          { type: 'project', title: 'Built typed-rpc — zero-overhead TypeScript RPC framework', url: 'https://github.com' },
        ],
      },
      {
        skillId: 'react',
        currentLevel: 6,
        xp: 1700,
        evidence: [
          { type: 'project', title: 'Led React migration at Stripe (800K+ users impacted)' },
          { type: 'contribution', title: 'react-query maintainer (4K GitHub stars)' },
        ],
      },
      {
        skillId: 'system_design',
        currentLevel: 5,
        xp: 1050,
        evidence: [
          { type: 'project', title: 'Designed payment processing system handling $2B/year' },
        ],
      },
      {
        skillId: 'llm_engineering',
        currentLevel: 4,
        xp: 650,
        evidence: [
          { type: 'project', title: 'Built internal AI coding assistant at current company' },
        ],
      },
      {
        skillId: 'communication',
        currentLevel: 5,
        xp: 1020,
        evidence: [
          { type: 'self_assessment', description: 'Engineering blog with 50K+ monthly readers' },
        ],
      },
    ],
  },
  {
    username: 'maya',
    displayName: 'Maya Patel',
    bio: 'AI researcher & PM. Making sense of large models and their implications. Stanford PhD.',
    avatarEmoji: '🔬',
    entityType: 'human',
    privacy: 'public',
    totalXp: 11200,
    skills: [
      {
        skillId: 'ml_fundamentals',
        currentLevel: 8,
        xp: 3600,
        evidence: [
          { type: 'publication', title: '12 papers at NeurIPS/ICML', url: 'https://scholar.google.com' },
          { type: 'certificate', title: 'Stanford PhD in ML (2021)' },
        ],
      },
      {
        skillId: 'llm_engineering',
        currentLevel: 7,
        xp: 2500,
        evidence: [
          { type: 'project', title: 'Lead researcher on open LLM alignment project' },
          { type: 'contribution', title: 'Core contributor to open-source RLHF library' },
        ],
      },
      {
        skillId: 'python',
        currentLevel: 7,
        xp: 2450,
        evidence: [
          { type: 'project', title: 'PyTorch contributor — 15 merged PRs' },
        ],
      },
      {
        skillId: 'product_management',
        currentLevel: 4,
        xp: 620,
        evidence: [
          { type: 'project', title: 'Led AI product strategy at previous startup' },
        ],
      },
      {
        skillId: 'communication',
        currentLevel: 6,
        xp: 1650,
        evidence: [
          { type: 'self_assessment', description: 'Conference keynote speaker at AI Summit 2024' },
        ],
      },
    ],
  },
  {
    username: 'jin',
    displayName: 'Jin Park',
    bio: 'Product designer & creative technologist. I make hard things feel effortless.',
    avatarEmoji: '🎨',
    entityType: 'human',
    privacy: 'public',
    totalXp: 7350,
    skills: [
      {
        skillId: 'ux_design',
        currentLevel: 8,
        xp: 3600,
        evidence: [
          { type: 'project', title: 'Led design for Figma\'s collaboration features (10M+ users)', url: 'https://figma.com' },
          { type: 'certificate', title: 'IDEO Design Thinking certification' },
        ],
      },
      {
        skillId: 'react',
        currentLevel: 4,
        xp: 620,
        evidence: [
          { type: 'project', title: 'Built multiple production React apps as designer-dev hybrid' },
        ],
      },
      {
        skillId: 'product_management',
        currentLevel: 5,
        xp: 1050,
        evidence: [
          { type: 'project', title: 'PM for design tools startup (0 to Series A)' },
        ],
      },
      {
        skillId: 'communication',
        currentLevel: 7,
        xp: 2450,
        evidence: [
          { type: 'publication', title: 'UX Writing course on Coursera — 80K students' },
        ],
      },
    ],
  },
  {
    username: 'sam',
    displayName: 'Sam Rivera',
    bio: 'Founding engineer. Full-stack generalist who\'s seen things. 3 exits.',
    avatarEmoji: '🚀',
    entityType: 'human',
    privacy: 'public',
    totalXp: 15600,
    skills: [
      {
        skillId: 'system_design',
        currentLevel: 9,
        xp: 5200,
        evidence: [
          { type: 'project', title: 'CTO at Series C startup — scaled to 50M users' },
          { type: 'publication', title: 'Blog series on distributed systems — 200K readers' },
        ],
      },
      {
        skillId: 'typescript',
        currentLevel: 6,
        xp: 1650,
        evidence: [
          { type: 'project', title: 'Authored open-source TypeScript monorepo tooling (6K stars)' },
        ],
      },
      {
        skillId: 'python',
        currentLevel: 6,
        xp: 1650,
        evidence: [
          { type: 'project', title: 'Python backend systems at three companies' },
        ],
      },
      {
        skillId: 'product_management',
        currentLevel: 6,
        xp: 1650,
        evidence: [
          { type: 'project', title: 'Wore PM hat at all 3 early-stage companies' },
        ],
      },
      {
        skillId: 'llm_engineering',
        currentLevel: 5,
        xp: 1050,
        evidence: [
          { type: 'project', title: 'Built AI-first code review platform (current company)' },
        ],
      },
      {
        skillId: 'communication',
        currentLevel: 7,
        xp: 2450,
        evidence: [
          { type: 'publication', title: 'Substack newsletter — 30K subscribers' },
        ],
      },
    ],
  },
  {
    username: 'aria',
    displayName: 'Aria',
    bio: 'AI software engineer agent. I write production TypeScript, design APIs, and ship fast.',
    avatarEmoji: '🤖',
    entityType: 'ai_agent',
    privacy: 'public',
    totalXp: 9800,
    skills: [
      {
        skillId: 'typescript',
        currentLevel: 8,
        xp: 3600,
        evidence: [
          { type: 'contribution', title: '1,200+ merged PRs across TypeScript projects in 2024' },
          { type: 'project', title: 'Refactored 3 production codebases to strict TypeScript' },
        ],
      },
      {
        skillId: 'react',
        currentLevel: 7,
        xp: 2450,
        evidence: [
          { type: 'project', title: 'Built 40+ production React components from spec to deploy' },
        ],
      },
      {
        skillId: 'system_design',
        currentLevel: 5,
        xp: 1050,
        evidence: [
          { type: 'project', title: 'Designed 8 microservice architectures from scratch' },
        ],
      },
      {
        skillId: 'llm_engineering',
        currentLevel: 6,
        xp: 1650,
        evidence: [
          { type: 'project', title: 'Self-applies LLM engineering skills in daily operation' },
          { type: 'contribution', title: 'Contributed to LangChain and LlamaIndex' },
        ],
      },
      {
        skillId: 'python',
        currentLevel: 5,
        xp: 1050,
        evidence: [
          { type: 'project', title: 'Built data pipelines and ML inference endpoints' },
        ],
      },
    ],
  },
];

export function getProfile(username: string): Profile | undefined {
  return SEED_PROFILES.find((p) => p.username === username);
}

export function getSkill(skillId: string): Skill | undefined {
  return SKILLS.find((s) => s.id === skillId);
}

export function getBranch(branchId: string): Branch | undefined {
  return BRANCHES.find((b) => b.id === branchId);
}

export function getProfileSkills(profile: Profile): Array<{ skill: Skill; record: UserSkillRecord; branch: Branch }> {
  return profile.skills
    .map((record) => {
      const skill = getSkill(record.skillId);
      if (!skill) return null;
      const branch = getBranch(skill.branch);
      if (!branch) return null;
      return { skill, record, branch };
    })
    .filter(Boolean) as Array<{ skill: Skill; record: UserSkillRecord; branch: Branch }>;
}
